wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1670325328.436601
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.5
      8:
      - 5
dataset:
  desc: null
  value:
    classification_classes:
    - 0
    - 30
    - 40
    - 55
    - 100
    dataset_path: ../datasets/EchoNet-Dynamic/
    label_div: 100
    label_string: EF
    mean: 0.1289
    name: echonet
    num_clips_per_vid: 3
    num_frames: 16
    num_frames_per_cycle: 64
    std: 0.1911
    test_clip_overlap: 0
    zoom_aug: true
eval:
  desc: null
  value:
    minimize: false
    standard: r2
    standards:
    - r2
    - mae
    - f1score
    - rmse
model:
  desc: null
  value:
    attention_encoder:
      fc_dropout_p: 0.5
      hidden_dim: 128
      name: node&edge
    checkpoint_path: null
    graph_regressor:
      dropout_p: 0.5
      fc_hidden_dim: 16
      gnn_hidden_dims:
      - 128
      - 64
      - 32
      name: gnn
    pretrained_path: null
    video_encoder:
      add_positional_embeddings: true
      cnn_dropout_p: 0.1
      fc_dropout_p: 0.5
      kernel_sizes: 3
      name: 3dconv
      out_channels:
      - 16
      - 32
      - 64
      - 128
      - 256
      output_dim: 256
      pool_sizes: 2
train:
  desc: null
  value:
    batch_size: 30
    criteria:
      classification:
        lambda: 0.001
        name: crossentropy
      regression:
        apply_shrinkage: false
        name: mae
        shrinkage_a: 0.0
        shrinkage_c: 0.0
      sparsity:
        edge_lambda: 0.0
        name: l1sparsity
        node_lambda: 0.0
    eval_visualization: false
    num_epochs: 100
    num_workers: 0
    optimizer:
      lr: 0.0001
      name: adam
      weight_decay: 1.0e-05
    print_model_stats: true
    sample_reweighting: false
    scheduler:
      gamma: 0.5
      milestones:
      - 50
      - 150
      - 200
      name: multi-step
    use_wandb: true
    wand_project_name: echognn
    wandb_mode: online
